package hoang.entity;
// Generated Mar 8, 2024, 9:41:02 AM by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher implements java.io.Serializable {

	private Integer publisherId;
	private Serializable publisherName;
	private String phone;
	private Serializable address;
	private Set books = new HashSet(0);

	public Publisher() {
	}

	public Publisher(Serializable publisherName, String phone, Serializable address, Set books) {
		this.publisherName = publisherName;
		this.phone = phone;
		this.address = address;
		this.books = books;
	}

	public Integer getPublisherId() {
		return this.publisherId;
	}

	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}

	public Serializable getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(Serializable publisherName) {
		this.publisherName = publisherName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}
