package hoang.entity;
// Generated Mar 6, 2024, 8:23:04 AM by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private BigInteger empId;
	private Department department;
	private Employee employee;
	private String empName;
	private String empNo;
	private Date hireDate;
	private byte[] image;
	private String job;
	private double salary;
	private Set employees = new HashSet(0);
	private Set timekeepers = new HashSet(0);

	public Employee() {
	}

	public Employee(BigInteger empId, Department department, Employee employee, String empName, String empNo, Date hireDate, String job,
			double salary) {
		this.empId = empId;
		this.department = department;
		this.employee = employee;
		this.empName = empName;
		this.empNo = empNo;
		this.hireDate = hireDate;
		this.job = job;
		this.salary = salary;
	}

	public BigInteger getEmpId() {
		return this.empId;
	}

	public void setEmpId(BigInteger empId) {
		this.empId = empId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

	public Set getTimekeepers() {
		return this.timekeepers;
	}

	public void setTimekeepers(Set timekeepers) {
		this.timekeepers = timekeepers;
	}

}
