package hoang.entity;
// Generated Mar 6, 2024, 8:23:04 AM by Hibernate Tools 5.6.15.Final

/**
 * SalaryGrade generated by hbm2java
 */
public class SalaryGrade implements java.io.Serializable {

	private int grade;
	private double highSalary;
	private double lowSalary;

	public SalaryGrade() {
	}

	public SalaryGrade(int grade, double highSalary, double lowSalary) {
		this.grade = grade;
		this.highSalary = highSalary;
		this.lowSalary = lowSalary;
	}

	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	public double getHighSalary() {
		return this.highSalary;
	}

	public void setHighSalary(double highSalary) {
		this.highSalary = highSalary;
	}

	public double getLowSalary() {
		return this.lowSalary;
	}

	public void setLowSalary(double lowSalary) {
		this.lowSalary = lowSalary;
	}

}
